---

- name: debian 12 requires bullseye aka oldstable
  when:
    - ansible_distribution.lower() == "debian"
    - ansible_distribution_major_version | int == 12
  block:

    - name: add bullseye repo
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        update_cache: true
        filename: bullseye
      with_items: "{{ oldstable_repos }}"

    - name: set /etc/apt/preferences
      ansible.builtin.copy:
        src: apt-preferences
        dest: /etc/apt/preferences
        owner: root
        mode: '0644'

- name: Install required packages for rundeck
  ansible.builtin.apt:
    name: "{{ rundeck_required_packages }}"
    update_cache: true
    install_recommends: false

- name: Copy rundeck apt keys
  ansible.builtin.copy:
    src: gpgkey
    dest: /usr/share/keyrings/rundeck.asc
    owner: root
    mode: '0644'

- name: rundeck repo
  ansible.builtin.apt_repository:
    repo: "{{ rundeck_repo }}"
    update_cache: true
    filename: rundeck

- name: install rundeck
  ansible.builtin.apt:
    name: "{{ rundeck_deb }}"
    update_cache: true
  notify: rundeck service

- name: install rundeck defaults
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/rundeckd
    owner: root
    group: rundeck
    mode: '0644'
  notify: rundeck service

- name: configure rundeck properties
  ansible.builtin.include_tasks: rundeckproperties.yml
  vars:
    rdeckpropfile: "{{ _rdeckconfig.key }}"
    rdeckpropcfg: "{{ _rdeckconfig.value }}"
  with_dict:
    - "{{ rundeck_config | default({}) }}"
  loop_control:
    loop_var: _rdeckconfig

- name: configure rundeck users and realms
  ansible.builtin.lineinfile:
    path: /etc/rundeck/realm.properties
    line: "{{ item.key }}:{{ item.value.pw | default('.*') }},{{ item.value.roles | default('.*') }}"
    regex: "^{{ item.key }}:.*"
    state: "{{ item.value.state | default('present') }}"
  notify: rundeck service
  with_dict: "{{ rundeck_users | default({}) }}"

- name: install plugins
  ansible.builtin.get_url:
    url: "{{ item.value }}"
    dest: "{{ rundeck_base }}/libext/{{ item.key }}"
    mode: '0644'
    owner: rundeck
    group: rundeck
  notify: rundeck service
  with_dict: "{{ rundeck_plugins }}"
  when: item.value != "absent"

- name: remove plugins
  ansible.builtin.file:
    path: "{{ rundeck_base }}/libext/{{ item.key }}"
    state: absent
  notify: rundeck service
  with_dict: "{{ rundeck_plugins }}"
  when: item.value == "absent"

- name: install additional files
  ansible.builtin.copy:
    src: "{{ item.key}}"
    dest: "{{ item.value }}"
    mode: '0640'
    owner: rundeck
    group: rundeck
  notify: rundeck service
  with_dict: "{{ rundeck_files }}"

- name: install additional files from templates
  ansible.builtin.template:
    src: "{{ item.key}}"
    dest: "{{ item.value }}"
    mode: '0640'
    owner: rundeck
    group: rundeck
  notify: rundeck service
  with_dict: "{{ rundeck_template_files }}"
